<?php

namespace Database\Seeders;

use App\Models\Asset;
use Illuminate\Database\Seeder;

class AssetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assets = [
            // Laptops
            [
                'asset_code' => 'AST-001',
                'name' => 'Dell Latitude 7420',
                'type' => 'Laptop',
                'brand' => 'Dell',
                'model' => 'Latitude 7420',
                'serial_number' => 'DL7420-001',
                'specs' => ['processor' => 'Intel Core i7', 'ram' => '16GB', 'storage' => '512GB SSD'],
                'location' => 'Gedung A - Lantai 1',
                'holder' => 'Ahmad Surya',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subMonths(8),
            ],
            [
                'asset_code' => 'AST-004',
                'name' => 'Lenovo ThinkPad T14s',
                'type' => 'Laptop',
                'brand' => 'Lenovo',
                'model' => 'ThinkPad T14s',
                'serial_number' => 'TP-T14S-022',
                'specs' => ['processor' => 'AMD Ryzen 7', 'ram' => '32GB', 'storage' => '1TB SSD'],
                'location' => 'Gedung B - Lantai 1',
                'holder' => 'Siti Nurhaliza',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subMonths(3),
            ],
            [
                'asset_code' => 'AST-007',
                'name' => 'MacBook Pro 14"',
                'type' => 'Laptop',
                'brand' => 'Apple',
                'model' => 'MacBook Pro',
                'serial_number' => 'MB-PRO-033',
                'specs' => ['processor' => 'Apple M1 Pro', 'ram' => '16GB', 'storage' => '512GB SSD'],
                'location' => 'Gedung A - Lantai 2',
                'holder' => 'Budi Hartono',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subMonths(6),
            ],
            [
                'asset_code' => 'AST-008',
                'name' => 'HP Pavilion 15',
                'type' => 'Laptop',
                'brand' => 'HP',
                'model' => 'Pavilion 15',
                'serial_number' => 'HP-PAV-044',
                'specs' => ['processor' => 'Intel Core i5', 'ram' => '8GB', 'storage' => '256GB SSD'],
                'location' => 'Gedung B - Lantai 2',
                'holder' => 'Ratna Dewi',
                'status' => 'ACTIVE',
                'condition' => 'FAIR',
                'purchased_at' => now()->subYear(),
            ],

            // Printers & Peripherals
            [
                'asset_code' => 'AST-002',
                'name' => 'HP LaserJet Pro M404n',
                'type' => 'Printer',
                'brand' => 'HP',
                'model' => 'LaserJet Pro M404n',
                'serial_number' => 'HP404N-015',
                'specs' => ['print_speed' => '40 ppm', 'duplex' => 'Automatic', 'connectivity' => 'USB, Ethernet'],
                'location' => 'Gedung A - Lantai 2',
                'holder' => 'Divisi IT',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subYear(),
            ],
            [
                'asset_code' => 'AST-009',
                'name' => 'Canon imagePRESS C6000',
                'type' => 'Multifunction Printer',
                'brand' => 'Canon',
                'model' => 'imagePRESS C6000',
                'serial_number' => 'CN-C6000-051',
                'specs' => ['print_speed' => '60 ppm', 'color' => 'Yes', 'connectivity' => 'USB, Ethernet, WiFi'],
                'location' => 'Gedung A - Lantai 1',
                'holder' => 'Bagian Administrasi',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subMonths(18),
            ],
            [
                'asset_code' => 'AST-010',
                'name' => 'Logitech MK735',
                'type' => 'Keyboard & Mouse',
                'brand' => 'Logitech',
                'model' => 'MK735',
                'serial_number' => 'LOG-MK735-062',
                'specs' => ['connectivity' => 'Wireless 2.4GHz', 'battery' => '18 months'],
                'location' => 'Gedung A - Lantai 1',
                'holder' => 'Handri Pranoto',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subMonths(4),
            ],

            // Servers & Network
            [
                'asset_code' => 'AST-003',
                'name' => 'Dell PowerEdge R640',
                'type' => 'Server',
                'brand' => 'Dell',
                'model' => 'PowerEdge R640',
                'serial_number' => 'PE-R640-007',
                'specs' => ['processor' => 'Dual Intel Xeon', 'ram' => '128GB', 'storage' => '2TB SSD'],
                'location' => 'Data Center',
                'holder' => 'Tim Infrastructure',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subYears(2),
            ],
            [
                'asset_code' => 'AST-005',
                'name' => 'Cisco Catalyst 2960',
                'type' => 'Switch',
                'brand' => 'Cisco',
                'model' => 'Catalyst 2960',
                'serial_number' => 'CC-2960-045',
                'specs' => ['ports' => '24', 'speed' => '1Gbps', 'poe' => 'Yes'],
                'location' => 'Network Room',
                'holder' => 'Tim Network',
                'status' => 'ACTIVE',
                'condition' => 'FAIR',
                'purchased_at' => now()->subYears(1)->subMonths(6),
            ],
            [
                'asset_code' => 'AST-011',
                'name' => 'Ubiquiti UniFi Dream Machine',
                'type' => 'Network Device',
                'brand' => 'Ubiquiti',
                'model' => 'Dream Machine',
                'serial_number' => 'UB-DM-073',
                'specs' => ['connectivity' => 'WiFi 6E', 'ports' => '4x1Gbps', 'storage' => '1TB'],
                'location' => 'Network Room',
                'holder' => 'Tim Network',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subMonths(5),
            ],

            // Displays & Monitors
            [
                'asset_code' => 'AST-006',
                'name' => 'Samsung 32" Monitor',
                'type' => 'Monitor',
                'brand' => 'Samsung',
                'model' => 'LU32R590C',
                'serial_number' => 'SM-32LU-089',
                'specs' => ['size' => '32 inch', 'resolution' => '4K UHD', 'panel' => 'VA'],
                'location' => 'Meeting Room A',
                'holder' => 'Meeting Room A',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subMonths(12),
            ],
            [
                'asset_code' => 'AST-012',
                'name' => 'Dell UltraSharp U2723DE',
                'type' => 'Monitor',
                'brand' => 'Dell',
                'model' => 'UltraSharp U2723DE',
                'serial_number' => 'DL-U2723DE-084',
                'specs' => ['size' => '27 inch', 'resolution' => '4K UHD', 'connectivity' => 'DP, HDMI, USB-C'],
                'location' => 'Gedung A - Lantai 1',
                'holder' => 'Gedung A - Lantai 1',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subMonths(7),
            ],

            // Other Equipment
            [
                'asset_code' => 'AST-013',
                'name' => 'Projector Epson EB-2250U',
                'type' => 'Projector',
                'brand' => 'Epson',
                'model' => 'EB-2250U',
                'serial_number' => 'EP-2250U-095',
                'specs' => ['brightness' => '5000 lumens', 'resolution' => 'WUXGA', 'connectivity' => 'HDMI, VGA'],
                'location' => 'Meeting Room B',
                'holder' => 'Meeting Room B',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subMonths(14),
            ],
            [
                'asset_code' => 'AST-014',
                'name' => 'APC Smart-UPS 5000VA',
                'type' => 'UPS',
                'brand' => 'APC',
                'model' => 'Smart-UPS 5000VA',
                'serial_number' => 'APC-5KVA-106',
                'specs' => ['capacity' => '5000VA', 'runtime' => '15 minutes at full load'],
                'location' => 'Data Center',
                'holder' => 'Tim Infrastructure',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subYears(1),
            ],
            [
                'asset_code' => 'AST-015',
                'name' => 'Backup SEAGATE Expansion 8TB',
                'type' => 'External Storage',
                'brand' => 'Seagate',
                'model' => 'Expansion 8TB',
                'serial_number' => 'SG-EXP-8TB-117',
                'specs' => ['capacity' => '8TB', 'connectivity' => 'USB 3.0'],
                'location' => 'Gedung A - Lantai 1',
                'holder' => 'Tim IT',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subMonths(10),
            ],
            [
                'asset_code' => 'AST-016',
                'name' => 'Cisco Meraki MR46',
                'type' => 'Access Point',
                'brand' => 'Cisco Meraki',
                'model' => 'MR46',
                'serial_number' => 'MR46-128',
                'specs' => ['standard' => 'WiFi 6', 'speed' => 'Up to 2.5 Gbps'],
                'location' => 'Gedung B - Lantai 1',
                'holder' => 'Tim Network',
                'status' => 'ACTIVE',
                'condition' => 'GOOD',
                'purchased_at' => now()->subMonths(9),
            ],
        ];

        foreach ($assets as $asset) {
            Asset::updateOrCreate(
                ['asset_code' => $asset['asset_code']],
                $asset
            );
        }
    }
}
